version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data.db:/app/data.db
    environment:
      - PORT=3000
      - JWT_SECRET=replace_with_strong_value
      - ADMIN_KEY=replace_admin_key
      - FRONTEND_URL=http://localhost:3000
      # - SMTP_HOST=...
      # - SMTP_USER=...
      # - SMTP_PASS=...
